name = "imdb-api"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-27"
kv_namespaces = [
         { binding = "CACHE", id = "02602279f443499ea4304c531035f701" }
]
